name: Frontend CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment.
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      # Step 3: Install project dependencies.
      - name: Install Dependencies
        run: npm install

      # Step 4: Run tests (if you have tests, otherwise this step will be skipped).
      - name: Run Tests
        run: npm run test --if-present

      # Step 5: Build the React application.
      - name: Build Application
        run: npm run build
